minimumReleaseAge: 1440
peerDependencyRules:
  allowedVersions:
    eslint: '10'
shamefullyHoist: true
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
